--
-- PostgreSQL database dump
--


-- Dumped from database version 15.19 (Debian 15.19-1.pgdg13+2)
-- Dumped by pg_dump version 15.19 (Debian 15.19-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cart_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_items (
                                   id bigint NOT NULL,
                                   created_at timestamp(6) without time zone,
                                   updated_at timestamp(6) without time zone,
                                   price_at_addition numeric(19,2),
                                   cart_id bigint,
                                   course_id bigint
);


--
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carts (
                              id bigint NOT NULL,
                              created_at timestamp(6) without time zone,
                              updated_at timestamp(6) without time zone,
                              total_price numeric(19,2),
                              student_id bigint
);


--
-- Name: carts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: certificates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.certificates (
                                     id bigint NOT NULL,
                                     created_at timestamp(6) without time zone,
                                     updated_at timestamp(6) without time zone,
                                     certificate_code character varying(100) NOT NULL,
                                     issued_at timestamp(6) without time zone NOT NULL,
                                     course_id bigint NOT NULL,
                                     student_id bigint NOT NULL
);


--
-- Name: certificates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.certificates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.certificates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course_progress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_progress (
                                        id bigint NOT NULL,
                                        created_at timestamp(6) without time zone,
                                        updated_at timestamp(6) without time zone,
                                        completed boolean NOT NULL,
                                        duration_seconds double precision,
                                        last_position_seconds double precision,
                                        last_watched_at timestamp(6) without time zone,
                                        max_position_seconds double precision,
                                        progress_percentage double precision,
                                        course_id bigint NOT NULL,
                                        student_id bigint NOT NULL
);


--
-- Name: course_progress_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses (
                                id bigint NOT NULL,
                                created_at timestamp(6) without time zone,
                                updated_at timestamp(6) without time zone,
                                current_enrolled integer NOT NULL,
                                description text,
                                is_purchasable boolean NOT NULL,
                                max_capacity integer NOT NULL,
                                name character varying(255),
                                price numeric(38,2),
                                teacher_id bigint,
                                image_url character varying(1000),
                                video_path character varying(1000)
);


--
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favorites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.favorites (
                                  id bigint NOT NULL,
                                  created_at timestamp(6) without time zone,
                                  updated_at timestamp(6) without time zone,
                                  course_id bigint NOT NULL,
                                  student_id bigint NOT NULL
);


--
-- Name: favorites_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.favorites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
                                      id bigint NOT NULL,
                                      created_at timestamp(6) without time zone,
                                      updated_at timestamp(6) without time zone,
                                      message text NOT NULL,
                                      is_read boolean,
                                      title character varying(200) NOT NULL,
                                      type character varying(50) NOT NULL,
                                      student_id bigint,
                                      teacher_id bigint
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_items (
                                    id bigint NOT NULL,
                                    created_at timestamp(6) without time zone,
                                    updated_at timestamp(6) without time zone,
                                    course_id bigint NOT NULL,
                                    course_name character varying(255) NOT NULL,
                                    price_at_purchase numeric(19,2) NOT NULL,
                                    teacher_id bigint,
                                    teacher_name character varying(255),
                                    order_id bigint NOT NULL
);


--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
                               id bigint NOT NULL,
                               created_at timestamp(6) without time zone,
                               updated_at timestamp(6) without time zone,
                               order_code character varying(255),
                               total_price numeric(19,2),
                               student_id bigint
);


--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_history (
                                        id bigint NOT NULL,
                                        created_at timestamp(6) without time zone,
                                        updated_at timestamp(6) without time zone,
                                        amount numeric(12,2) NOT NULL,
                                        course_name character varying(255) NOT NULL,
                                        payment_method character varying(50) NOT NULL,
                                        purchased_at timestamp(6) without time zone NOT NULL,
                                        status character varying(50) NOT NULL,
                                        transaction_code character varying(100) NOT NULL,
                                        course_id bigint NOT NULL,
                                        student_id bigint NOT NULL
);


--
-- Name: payment_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_courses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_courses (
                                        student_id bigint NOT NULL,
                                        course_id bigint NOT NULL
);


--
-- Name: students; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.students (
                                 id bigint NOT NULL
);


--
-- Name: teachers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teachers (
                                 id bigint NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
                              id bigint NOT NULL,
                              email character varying(255) NOT NULL,
                              name character varying(255),
                              password character varying(255) NOT NULL,
                              role character varying(255) NOT NULL,
                              CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['STUDENT'::character varying, 'TEACHER'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- Name: carts carts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);


--
-- Name: certificates certificates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificates
    ADD CONSTRAINT certificates_pkey PRIMARY KEY (id);


--
-- Name: course_progress course_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_progress
    ADD CONSTRAINT course_progress_pkey PRIMARY KEY (id);


--
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);


--
-- Name: favorites favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: payment_history payment_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_history
    ADD CONSTRAINT payment_history_pkey PRIMARY KEY (id);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- Name: teachers teachers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_pkey PRIMARY KEY (id);


--
-- Name: certificates uk61fmvtjit9xp7jdb6ivcolk32; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificates
    ADD CONSTRAINT uk61fmvtjit9xp7jdb6ivcolk32 UNIQUE (student_id, course_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: course_progress uk8pmoq4mvfp172mmywpmg7muf2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_progress
    ADD CONSTRAINT uk8pmoq4mvfp172mmywpmg7muf2 UNIQUE (student_id, course_id);


--
-- Name: payment_history uk9ko1k6brkj4unq0q9r7qov4sk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_history
    ADD CONSTRAINT uk9ko1k6brkj4unq0q9r7qov4sk UNIQUE (transaction_code);


--
-- Name: cart_items uk_cart_items_cart_course; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT uk_cart_items_cart_course UNIQUE (cart_id, course_id);


--
-- Name: carts uk_carts_student; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT uk_carts_student UNIQUE (student_id);


--
-- Name: student_courses uk_student_courses_student_course; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_courses
    ADD CONSTRAINT uk_student_courses_student_course UNIQUE (student_id, course_id);


--
-- Name: favorites ukikfh10rywsn4c4cti29ravgj7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT ukikfh10rywsn4c4cti29ravgj7 UNIQUE (student_id, course_id);


--
-- Name: certificates ukilkogva3i6dm8ngpqipamo70y; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificates
    ADD CONSTRAINT ukilkogva3i6dm8ngpqipamo70y UNIQUE (certificate_code);


--
-- Name: carts ukraflf7tp6hf3rpyuw68b8rv82; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT ukraflf7tp6hf3rpyuw68b8rv82 UNIQUE (student_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: favorites fk18gn3il3auwv7m74x50p9y479; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT fk18gn3il3auwv7m74x50p9y479 FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- Name: course_progress fk3h5cnaawt3y91eeaaloat1swr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_progress
    ADD CONSTRAINT fk3h5cnaawt3y91eeaaloat1swr FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- Name: courses fk468oyt88pgk2a0cxrvxygadqg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fk468oyt88pgk2a0cxrvxygadqg FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);


--
-- Name: students fk7xqmtv7r2eb5axni3jm0a80su; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fk7xqmtv7r2eb5axni3jm0a80su FOREIGN KEY (id) REFERENCES public.users(id);


--
-- Name: payment_history fk9qqhdaufk2w6rbdf58jppwobc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_history
    ADD CONSTRAINT fk9qqhdaufk2w6rbdf58jppwobc FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: course_progress fkc7kqnu3il1dir2rxceoteaf1h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_progress
    ADD CONSTRAINT fkc7kqnu3il1dir2rxceoteaf1h FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: payment_history fkcf8j8y6g38wxkg6hwyf0spmjp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_history
    ADD CONSTRAINT fkcf8j8y6g38wxkg6hwyf0spmjp FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: orders fkeudclkhb1qymuoqf76gg10i3t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkeudclkhb1qymuoqf76gg10i3t FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: cart_items fkivp3vwkw2egm5ekoapk31iqs6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fkivp3vwkw2egm5ekoapk31iqs6 FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- Name: favorites fkl7ri0b5o5nxdvrlcu5g8ekruk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT fkl7ri0b5o5nxdvrlcu5g8ekruk FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: notifications fklchct0805t9w7mapbehsi6dcw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fklchct0805t9w7mapbehsi6dcw FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: notifications fkmm546q93nlcswk91qucxmjnsg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fkmm546q93nlcswk91qucxmjnsg FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);


--
-- Name: teachers fkpavufmal5lbtc60csriy8sx3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT fkpavufmal5lbtc60csriy8sx3 FOREIGN KEY (id) REFERENCES public.users(id);


--
-- Name: certificates fkpc7mh1qdwwhawk8k3d8cw5y19; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificates
    ADD CONSTRAINT fkpc7mh1qdwwhawk8k3d8cw5y19 FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: cart_items fkpcttvuq4mxppo8sxggjtn5i2c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES public.carts(id);


--
-- Name: carts fkrq5a3tu77vtmk1m004na7al7k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT fkrq5a3tu77vtmk1m004na7al7k FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: certificates fks5rftqrsgkog7h4piv3f7a9s6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificates
    ADD CONSTRAINT fks5rftqrsgkog7h4piv3f7a9s6 FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- Name: student_courses fksfpq78oyrqua1h0obpl7ulc18; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_courses
    ADD CONSTRAINT fksfpq78oyrqua1h0obpl7ulc18 FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- Name: student_courses fkwj1l0mta35u161acdl2tupoo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_courses
    ADD CONSTRAINT fkwj1l0mta35u161acdl2tupoo FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- PostgreSQL database dump complete
--
