-- ============================================================
-- TEACHER REGISTRATION REQUESTS
-- ============================================================

CREATE TABLE public.teacher_registration_requests (

                                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                                      name VARCHAR(255) NOT NULL,

                                                      email VARCHAR(255) NOT NULL,

                                                      status VARCHAR(30) NOT NULL,

                                                      verification_code_hash VARCHAR(255),

                                                      code_expires_at TIMESTAMP,

                                                      requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                                      code_sent_at TIMESTAMP,

                                                      rejected_at TIMESTAMP,

                                                      completed_at TIMESTAMP,

                                                      CONSTRAINT teacher_registration_status_check
                                                          CHECK (
                                                              status IN (
                                                                         'PENDING',
                                                                         'CODE_SENT',
                                                                         'REJECTED',
                                                                         'COMPLETED'
                                                                  )
                                                              )
);


-- Aynı e-posta için aynı anda ikinci aktif başvuru oluşmasın.
CREATE UNIQUE INDEX uk_teacher_registration_active_email
    ON public.teacher_registration_requests (LOWER(email))
    WHERE status IN ('PENDING', 'CODE_SENT');


-- Admin panelinde bekleyen başvuruları hızlı listelemek için.
CREATE INDEX idx_teacher_registration_status_requested
    ON public.teacher_registration_requests (
                                             status,
                                             requested_at DESC
        );