CREATE TABLE user_sessions (

                               id BIGINT GENERATED BY DEFAULT AS IDENTITY
                                   PRIMARY KEY,

                               session_id VARCHAR(36) NOT NULL,

                               user_id BIGINT NOT NULL,

                               role VARCHAR(20) NOT NULL,

                               login_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

                               last_seen_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

                               logout_at TIMESTAMP(6) WITHOUT TIME ZONE,

                               active_seconds BIGINT NOT NULL DEFAULT 0,

                               expires_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

                               status VARCHAR(20) NOT NULL,

                               CONSTRAINT uq_user_sessions_session_id
                                   UNIQUE (session_id),

                               CONSTRAINT fk_user_sessions_user
                                   FOREIGN KEY (user_id)
                                       REFERENCES users(id)
                                       ON DELETE CASCADE,

                               CONSTRAINT chk_user_sessions_role
                                   CHECK (
                                       role IN (
                                                'STUDENT',
                                                'TEACHER',
                                                'ADMIN'
                                           )
                                       ),

                               CONSTRAINT chk_user_sessions_status
                                   CHECK (
                                       status IN (
                                                  'ACTIVE',
                                                  'LOGGED_OUT',
                                                  'EXPIRED'
                                           )
                                       ),

                               CONSTRAINT chk_user_sessions_active_seconds
                                   CHECK (
                                       active_seconds >= 0
                                       )
);


CREATE INDEX idx_user_sessions_user_id
    ON user_sessions(user_id);


CREATE INDEX idx_user_sessions_status
    ON user_sessions(status);


CREATE INDEX idx_user_sessions_last_seen
    ON user_sessions(last_seen_at);


CREATE INDEX idx_user_sessions_login_at
    ON user_sessions(login_at);